spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_telematics
spring.datasource.username=telematics
spring.datasource.password=telematics
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration